#!/usr/bin/zsh
#
# Environment variables for every shell
#


export PATH="${HOME}/.local/bin:${PATH}"

export XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-${HOME}/.cache}

#export ASDF_CONFIG_FILE=${XDG_CONFIG_HOME}/asdf/asdfrc
#export ASDF_DIR=${XDG_DATA_HOME}/asdf
#export ASDF_DATA_DIR=${XDG_CACHE_HOME}/asdf
